POST http://localhost:3003/api/readinglists
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfdXNlckBtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2NjAyOTc1OTR9.4pxX9YdpUJQsP_H9xD-ZUQY7pwQz0aHAjsURPJjk6Oo

{
  "blog_id": 5,
  "user_id": 1
}